### ISSUE TITLE
English localization

### ISSUE THREAD

**Issue by serhii-londar** [powerwolf543/CheckDuplicateFileName#1]
Can you add English localization?
It would be great! Thank for your hard work.

**Comment by powerwolf543** [comment]
> Can you add English localization?
> It would be great! Thank for your hard work.

@serhii-londar , Thanks for your comment. I am updating the application that would include the **localizations**. Hopefully it would be released soon.

**Comment by powerwolf543** [comment]
Hi @serhii-londar,  The build [1.6.1](https://github.com/powerwolf543/DuplicateFinder/releases/) has been released which includes the localization.
